export const products = [
  {
    id: "64a654593e91b8e73a351e9b",
    name: "iPhone 14",
    description: "Short description",
    price: 2999,
    brand: "Apple",
    category: "Phone",
    inStock: true,
    image: "https://m.media-amazon.com/images/I/71ZOtNdaZCL._AC_SL1500_.jpg",
    reviews: [],
  },
  {
    id: "64a4ebe300900d44bb50628a",
    name: "Logitech MX",
    description: "Perfect stroke keys with ergonomic design",
    price: 102.99,
    brand: "Logitech",
    category: "Accessories",
    inStock: true,
    image: "https://m.media-amazon.com/images/I/71ZOtNdaZCL._AC_SL1500_.jpg",
    reviews: [],
  },
  {
    id: "648437b38c44d52b9542e340",
    name: "Apple iPhone 12, 64GB",
    description: "Refurbished iPhone 12 in excellent condition",
    price: 4000,
    brand: "Apple",
    category: "Phone",
    inStock: true,
    image: "https://m.media-amazon.com/images/I/71ZOtNdaZCL._AC_SL1500_.jpg",
    reviews: [],
  },
  {
    id: "64a4e9e77e7299078334019f",
    name: "Logitech MX Master",
    description: "Advanced ergonomic wireless mouse",
    price: 7000,
    brand: "Logitech",
    category: "Accessories",
    inStock: true,
    image: "https://m.media-amazon.com/images/I/71ZOtNdaZCL._AC_SL1500_.jpg",
    reviews: [],
  },
  {
    id: "649d775128b6744f0f497040",
    name: "Smart Watch (Answer/Make Call)",
    description: "Bluetooth call and message reminder smartwatch",
    price: 5000,
    brand: "Nerunsa",
    category: "Watch",
    inStock: true,
    image: "https://m.media-amazon.com/images/I/71ZOtNdaZCL._AC_SL1500_.jpg",
    reviews: [],
  },
];
