export const products = [
  {
    id: "64a654593e91b8e73a351e9b",
    name: "iPhone 14",
    description: "Short description",
    price: 2999,
    brand: "Apple",
    category: "Phone",
    inStock: false,
    image: "https://m.media-amazon.com/images/I/71ZOtNdaZCL._AC_SL1500_.jpg",
    reviews: [
      { id:"1", user: "Ali", rating: 5, comment: "Harika bir telefon, çok hızlı!" },
      { id:"2", user: "Zeynep", rating: 4, comment: "Kamera mükemmel ama pil ömrü biraz kısa." },
    ],
  },
  {
    id: "64a4ebe300900d44bb50628a",
    name: "Logitech MX",
    description: "Perfect stroke keys with ergonomic design",
    price: 102.99,
    brand: "Logitech",
    category: "Accessories",
    inStock: true,
    image: "https://m.media-amazon.com/images/I/71ZOtNdaZCL._AC_SL1500_.jpg",
    reviews: [
      { id:"1", user: "Mehmet", rating: 5, comment: "Klavyenin hissiyatı çok iyi, sessiz ve ergonomik." },
      { id:"2", user: "Ayşe", rating: 4, comment: "Tuşlar biraz büyük ama alışınca rahat." },
    ],
  },
  {
    id: "648437b38c44d52b9542e340",
    name: "Apple iPhone 12, 64GB",
    description: "Refurbished iPhone 12 in excellent condition",
    price: 4000,
    brand: "Apple",
    category: "Phone",
    inStock: true,
    image: "https://m.media-amazon.com/images/I/71ZOtNdaZCL._AC_SL1500_.jpg",
    reviews: [
      { id:"1", user: "Burak", rating: 5, comment: "Fiyatına göre harika bir telefon." },
      { id:"2", user: "Elif", rating: 3, comment: "Şarj biraz çabuk bitiyor ama performansı iyi." },
    ],
  },
  {
    id: "64a4e9e77e7299078334019f",
    name: "Logitech MX Master",
    description: "Advanced ergonomic wireless mouse",
    price: 7000,
    brand: "Logitech",
    category: "Accessories",
    inStock: true,
    image: "https://m.media-amazon.com/images/I/71ZOtNdaZCL._AC_SL1500_.jpg",
    reviews: [
      { id:"1", user: "Cem", rating: 5, comment: "Ellerim büyük olduğu için çok rahat." },
      { id:"2", user: "Ebru", rating: 4, comment: "Pil ömrü harika ama biraz pahalı." },
    ],
  },
  {
    id: "649d775128b6744f0f497040",
    name: "Smart Watch (Answer/Make Call)",
    description: "Bluetooth call and message reminder smartwatch",
    price: 5000,
    brand: "Nerunsa",
    category: "Watch",
    inStock: true,
    image: "https://m.media-amazon.com/images/I/71ZOtNdaZCL._AC_SL1500_.jpg",
    reviews: [
      { id:"1", user: "Deniz", rating: 5, comment: "Çağrı yanıtlamak çok kolay, çok memnunum." },
      {  id:"2", user: "Seda", rating: 3, comment: "Batarya süresi daha uzun olabilirdi." },
    ],
  },
];
